### ISSUE TITLE
[FEATURE]北洋发种页有问题

### ISSUE THREAD

**Issue by ma3252788** [techmovie/easy-seed#26]
**这个功能是否与某个问题相关**

北洋发种页无法自动填写标题，虽然自动选择了类别，但是子类别并没有自动出现和填写。

![](https://ypyssl.machunjie.com/machunjie/20210321105740.png)

正常应该弹出：

![](https://ypyssl.machunjie.com/machunjie/20210321105826.png_machunjie.png)

**描述你的期望功能**
自动弹出子菜单并自动填写

**描述你的替代方案**
目前只能手动先点击其他类别，再点回来才能弹出子菜单。然后手动填写信息。

**额外信息**
无

**Comment by techmovie** [comment]
在有豆瓣简介的情况下，以下表单没有实现自动填写，之后也暂不考虑实现：
* 纪录片中的 **纪录片类型** **字幕情况**
* 综艺中的 发行时间 **节目内容** **字幕情况**
