### ISSUE TITLE
[ HUiJvTT]

### ISSUE THREAD

**Issue by SNSD-CMD** [techmovie/easy-seed#29]
* 站点地址：http://huijvtt.com/torrents.php
* 站点架构：NP
* 站点是否限制发布权限：无
* 站点发布种子所需的用户等级：(堕落者)Peasant
* 其他信息：

**Comment by techmovie** [comment]
属于新开站，如果发布页已经确定下来的话，可以考虑支持。

**Comment by techmovie** [comment]
> 属于新开站，如果发布页已经确定下来的话，可以考虑支持。

音乐站短时间内不会支持 issue先关了。
