### ISSUE TITLE
[BUG]脚本兼容性问题

### ISSUE THREAD

**Issue by whyjxz14** [techmovie/easy-seed#32]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：
* 浏览器版本：
* 所用用户脚本扩展名称：
* easy-seed版本：
1.1.1
**问题描述**
似乎和https://sleazyfork.org/scripts/32651-m-team%E5%A4%A7%E5%9B%BE%E6%B5%8F%E8%A7%88/code/m-team%E5%A4%A7%E5%9B%BE%E6%B5%8F%E8%A7%88.user.js
这个大图浏览脚本不兼容，能看一下怎么可以修改吗。

**复现步骤**

**问题截图**

**Comment by techmovie** [comment]
1.1.2已修复
