### ISSUE TITLE
[BUG] 皮上转被report的种子会将report内容当成转载描述

### ISSUE THREAD

**Issue by scatking** [techmovie/easy-seed#33]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：Firefox
* 浏览器版本：87.0 （64）
* 所用用户脚本扩展名称：Tamper monkey
* easy-seed版本：v1.1.1

**问题描述**
在转载皮上被report的种子时，会将report内容当成描述。

**复现步骤**
1. 找到一个被report的种子，如：245121
2. 转载

**问题截图**
![](https://images2.imgbox.com/aa/b5/oO1ghi95_o.png)

**Comment by techmovie** [comment]
1.1.2已修复
