### ISSUE TITLE
[FEATURE] 将BHD的描述截图bbcode改为[img=350x350]  [/img]

### ISSUE THREAD

**Issue by scatking** [techmovie/easy-seed#34]
**这个功能是否与某个问题相关**
BHD发种需要略缩图

**描述你的期望功能**
现在的方案是转为略缩图后再发布，但是这样似乎之后转载到其他站点也是略缩图了，不是很方便。
BHD的bbcode支持[img=350x350]  [/img]的写法强制显示略缩图，这这样可能比较方便。

**描述你的替代方案**
无

**额外信息**

**Comment by techmovie** [comment]
1.1.2已增加此功能

**Comment by ted423** [comment]
Please see below the message from the staff member:

Screenshot thumbnails aren't clickable

**Comment by ted423** [comment]
建议这样 
[url=https://ptpimg.me/p9kv4w.png][img=350x350]https://ptpimg.me/p9kv4w.png[/img][/url]

**Comment by techmovie** [comment]
@ted423 #38

**Comment by scatking** [comment]
> 建议这样
> [url=https://ptpimg.me/p9kv4w.png][img=350x350][https://ptpimg.me/p9kv4w.png[/img][/url]](https://ptpimg.me/p9kv4w.png%5B/img%5D%5B/url%5D)

https://github.com/techmovie/easy-seed/issues/38

这个我提过一个新的issue,树大好像已经更新了
https://github.com/techmovie/easy-seed/commit/63c8b44fd7d6b69de5776e409fe09bf190b675b0
