### ISSUE TITLE
[BUG]greasyfork 其实不支持混淆代码

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-seed#37]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：
* 浏览器版本：
* 所用用户脚本扩展名称：
* easy-seed版本：

**问题描述**
https://greasyfork.org/zh-CN/help/code-rules
提交到 Greasy Fork 的代码不得混淆或最小化。用户必须能有机会能在安装前审视并理解脚本的内容。如果脚本使用 WebPack 之类的工具打包，你必须在打包参数指定不进行最小化处理。
**复现步骤**

**问题截图**

**Comment by ted423** [comment]
之前遇到的讨论
https://greasyfork.org/zh-CN/scripts/11915-anti-redirect/discussions/19037
label好像写错了

**Comment by techmovie** [comment]
@ted423 下版改掉吧
