### ISSUE TITLE
[FEATURE] 关于BHD的的bbcode

### ISSUE THREAD

**Issue by scatking** [techmovie/easy-seed#38]
**这个功能是否与某个问题相关**
在BHD发种时被管理告知略缩图必须附带上链接，否则无法通过。

**描述你的期望功能**
将图片的bbcode修改为 ``` [url=<imgurl>][img=350x350]<imgurl>[/img][/url]```

**描述你的替代方案**
无

**额外信息**

**Comment by techmovie** [comment]
@scatking 最新版已经实现了

**Comment by scatking** [comment]
> 
> 
> @scatking 最新版已经实现了

实现的应该是[350x350]吧，BHD的管理说图片必须要能带链接的。 所以其实需要在外面套一个[url=<imgurl>]的bbcode

**Comment by techmovie** [comment]
@scatking 了解了。如果缩略图不是必须350*350的尺寸，可以用转缩略图的功能。先点击转缩略图按钮，再进行转载。

**Comment by scatking** [comment]
就是这样的话得分两次转感觉会有一点麻烦。
如果可以加一个正则匹配不到[url]就套上去的话可能会更直接一点。

（我也没用npm写过js脚本不知道从哪下手改动提PR，就只能开个issue看看了。）

**Comment by techmovie** [comment]
@scatking 如果url里的地址不是真正的缩略图而直接把原图放上去，感觉也没啥意义。

**Comment by scatking** [comment]
url里面的地址不能是略缩图的，一般是用来点进去看原图区分视频质量的。
略缩图才是用来预览的。
确实啥意义，都是一张图，只能说适配站点规则。

**Comment by techmovie** [comment]
@scatking 哦 刚刚我说反了。如果BHD允许两张图是同一张图的话，那我改下。

**Comment by ted423** [comment]
尴尬了，是还没release么？

**Comment by techmovie** [comment]
@ted423 还没 得下个版本了

**Comment by ted423** [comment]
缩略图点转载
然后变这样了
[url=https://pixhost.to/show/132/200788693_cz54s0.png][img=350x350]https://pixhost.to/show/132/200788693_cz54s0.png[/img][/url][url=https://pixhost.to/show/132/200788694_q8567s.png][img=350x350]https://pixhost.to/show/132/200788694_q8567s.png[/img][/url][url=https://pixhost.to/show/132/200788696_yx1131.png][img=350x350]https://pixhost.to/show/132/200788696_yx1131.png[/img][/url][url=https://pixhost.to/show/132/200788697_899s8v.png][img=350x350]https://pixhost.to/show/132/200788697_899s8v.png[/img][/url][url=https://pixhost.to/show/132/200788698_0o8410.png][img=350x350]https://pixhost.to/show/132/200788698_0o8410.png[/img][/url][url=https://pixhost.to/show/132/200788699_9ogdf7.png][img=350x350]https://pixhost.to/show/132/200788699_9ogdf7.png[/img][/url]

**Comment by ted423** [comment]
弄错，看起来似乎语法没问题，只是没显示

**Comment by ted423** [comment]
似乎挂了

**Comment by techmovie** [comment]
> 似乎挂了

![image](https://user-images.githubusercontent.com/59314774/144777887-42b15b72-d6e6-4d6b-a723-914bad088471.png)
![image](https://user-images.githubusercontent.com/59314774/144777893-e33f852b-2e44-4c10-950f-ae114c6b37c2.png)
这样不对么？

**Comment by scatking** [comment]
没问题吧

**Comment by ted423** [comment]
> > 似乎挂了
> 
> ![image](https://user-images.githubusercontent.com/59314774/144777887-42b15b72-d6e6-4d6b-a723-914bad088471.png) ![image](https://user-images.githubusercontent.com/59314774/144777893-e33f852b-2e44-4c10-950f-ae114c6b37c2.png) 往那这样不对么？

不知道我们从皮

> > 似乎挂了
> 
> ![image](https://user-images.githubusercontent.com/59314774/144777887-42b15b72-d6e6-4d6b-a723-914bad088471.png) ![image](https://user-images.githubusercontent.com/59314774/144777893-e33f852b-2e44-4c10-950f-ae114c6b37c2.png) 这样不对么？

我从皮网上转就是源的，猫站转的我倒是

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/144794040-cd56d091-b998-4e08-985c-b348f3c79798.png)

**Comment by ted423** [comment]
皮/torrents.php?id=5652&torrentid=179170
![image](https://user-images.githubusercontent.com/7042766/144794142-f8c7f0b7-bd9b-4d6a-ab0b-e5cfd644ca7a.png)

版本2.4.3

**Comment by techmovie** [comment]
> 皮/torrents.php?id=5652&torrentid=179170 ![image](https://user-images.githubusercontent.com/7042766/144794142-f8c7f0b7-bd9b-4d6a-ab0b-e5cfd644ca7a.png)
> 
> 版本2.4.3

这种格式的写法很常见么？不常见的话就不去兼容它了

**Comment by ted423** [comment]
> > 皮/torrents.php?id=5652&torrentid=179170 ![image](https://user-images.githubusercontent.com/7042766/144794142-f8c7f0b7-bd9b-4d6a-ab0b-e5cfd644ca7a.png)
> > 版本2.4.3
> 
> 这种格式的写法很常见么？不常见的话就不去兼容它了

我也不太懂，这是同条列下remux Hifi的结果
![image](https://user-images.githubusercontent.com/7042766/144803101-922ea008-30af-4326-aa71-11c3c6289e76.png)

按道理这个都应该是html代码转换的？

**Comment by ted423** [comment]
EA 则是只有对比图正常

[img]http://ptpimg.me/rf67gy.png[/img]

[img]http://ptpimg.me/ccn1g8.png[/img]

[img]http://ptpimg.me/20e455.png[/img]

SOURCE vs. ENCODE: [quote]
[url=[url=https://ptpimg.me/09n79s.png][img=350x350]https://ptpimg.me/09n79s.png[/img][/url]][img]http://thumbnails106.imagebam.com/23580/698e90235792559.jpg[/img][/url] [url=[url=https://ptpimg.me/4870y3.png][img=350x350]https://ptpimg.me/4870y3.png[/img][/url]][img]http://thumbnails101.imagebam.com/23580/e25835235793133.jpg[/img][/url]

**Comment by techmovie** [comment]
> 按道理这个都应该是html代码转换的？

从这里拿的。/torrents.php?action=get_description&id=179170
现在只匹配了`[img]xxxx[/img]`这种格式

**Comment by ted423** [comment]
@techmovie 看来老版本可能img=这种写法会比较多...
