### ISSUE TITLE
[FEATURE]希望加个设置项，可以隐藏平时很少用的站点

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-seed#42]
**这个功能是否与某个问题相关**

**描述你的期望功能**
目前的列表有点长，找的时候会比较久

**描述你的替代方案**

**额外信息**

**Comment by techmovie** [comment]
@ted423 点一键转种旁边的设置icon就可以设置了。

**Comment by ted423** [comment]
好吧。。。我以为那个是煎蛋

**Comment by techmovie** [comment]
@onylin 提个issue吧 在额外功能关闭那里再新增一个「快速检索关闭」选项
