### ISSUE TITLE
[BUG]Pter非英语资源，地区需要选择其它(Other)

### ISSUE THREAD

**Issue by techmovie** [techmovie/easy-seed#45]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：
* 浏览器版本：
* 所用用户脚本扩展名称：
* easy-seed版本：

**问题描述**
Pter非英语资源，地区需要选择其它(Other)

**复现步骤**

**问题截图**

**Comment by ted423** [comment]
@techmovie 这个会不会太细了😂

**Comment by techmovie** [comment]
@ted423 防不胜防的规则...
