### ISSUE TITLE
[BUG] PTer无法显示转种框架

### ISSUE THREAD

**Issue by scatking** [techmovie/easy-seed#46]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：Firefox
* 浏览器版本：87.0 （64）
* 所用用户脚本扩展名称：Tamper monkey
* easy-seed版本：v1.2.0

**问题描述**
猫站种子页面没有转种框架注入，其他站均正常

**复现步骤**
任意进入一个猫站的种子页面即可。

**问题截图**

![Snipaste_2021-04-10_13-31-54.png](https://i.loli.net/2021/04/10/wSpxvTZUNJL3H6Y.png)

**Comment by techmovie** [comment]
可以截一下标题附近么

**Comment by scatking** [comment]
这样可以吗：
![Snipaste_2021-04-10_15-08-40.png](https://i.loli.net/2021/04/10/i3vAbe6INtxPHo8.png)

**Comment by techmovie** [comment]
@scatking 看上去标题下面还有其他东西，跟普通用户的不一样。我改下选择器。

**Comment by scatking** [comment]
好像确实是多了个元素的问题，应该是多了个这个：
<a href="#tohelper">Jump To Helper Area</a>

**Comment by ted423** [comment]
话说我用1.2.0在猫站往外转没有imdb和douban url的自动填写了

**Comment by techmovie** [comment]
@ted423 是种子描述本身没有这两个链接吧
