### ISSUE TITLE
[BUG] 更新后无法转种

### ISSUE THREAD

**Issue by scatking** [techmovie/easy-seed#47]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：Firefox 87.0 (64 位)  / Microsoft Edge版本 89.0.774.76 (官方内部版本) (64 位) / Chrome 版本 90.0.4430.72（正式版本） （64 位）
* 浏览器版本：参照上文
* 所用用户脚本扩展名称：Tamper monkey
* easy-seed版本：1.2.2

**问题描述**
点击按钮转种后跳转至其他站点但是无法自动填充内容。
已测试源站点：PTer BHD TCCF
已测试目标站点：PTer BHD TCCF

**复现步骤**
点击转种按钮

**问题截图**

**Comment by techmovie** [comment]
能否帮忙测试一下我这个修改后的脚本。https://gist.github.com/techmovie/8383241251ea34291f1184fc515868cd/raw/741c605be9f8d5b8bb8aaa70f78386fed54aa48b/easy-seed-%25E6%25B5%258B%25E8%25AF%2595%25E7%2589%2588.user.js
1.2.3先临时替换回之前的参数传递方式，后续的还会继续考虑切换到objectUrl的方式。

**Comment by scatking** [comment]
Firefox 测试还是无法转种

**Comment by techmovie** [comment]
@scatking 火狐也是Tamper monkey么？其他浏览器没问题了？

**Comment by scatking** [comment]
是的，其他浏览器我没试过😂

**Comment by techmovie** [comment]
我这也有问题，应该是火狐的问题。暂时不考虑切换参数传递的方式了。
