### ISSUE TITLE
[BUG]内站带链接的图片转外站相关问题

### ISSUE THREAD

**Issue by scatking** [techmovie/easy-seed#48]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：Firefox
* 浏览器版本：87.0 (64 位)
* 所用用户脚本扩展名称：Tampermonkey
* easy-seed版本：1.2.3

**问题描述**
带链接的图片转载到外站（已测试BHD BLU ITS），似乎会把链接内容当成图片链接，导致转过去的都是无效图片

**复现步骤**
转载任意带链接的种子（ie. 天空的179143）至外站

**问题截图**
[![c4UzFO.png](https://z3.ax1x.com/2021/04/17/c4UzFO.png)](https://imgtu.com/i/c4UzFO)
[![c4ai6A.png](https://z3.ax1x.com/2021/04/17/c4ai6A.png)](https://imgtu.com/i/c4ai6A)

**Comment by techmovie** [comment]
这种情况是是因为图片[url=link]里不是带图片后缀的直链，本来是想通过这个link来原图的。
这种情况的话我改成取[img][/img]里的的地址吧。

**Comment by techmovie** [comment]
> 这种情况是是因为图片[url=link]里不是带图片后缀的直链，本来是想通过这个link来获取原图的。
> 这种情况的话我改成取[img][/img]里的的地址吧。

缩略图点转载
然后变这样了
[url=https://pixhost.to/show/132/200788693_cz54s0.png][img=350x350]https://pixhost.to/show/132/200788693_cz54s0.png[/img][/url][url=https://pixhost.to/show/132/200788694_q8567s.png][img=350x350]https://pixhost.to/show/132/200788694_q8567s.png[/img][/url][url=https://pixhost.to/show/132/200788696_yx1131.png][img=350x350]https://pixhost.to/show/132/200788696_yx1131.png[/img][/url][url=https://pixhost.to/show/132/200788697_899s8v.png][img=350x350]https://pixhost.to/show/132/200788697_899s8v.png[/img][/url][url=https://pixhost.to/show/132/200788698_0o8410.png][img=350x350]https://pixhost.to/show/132/200788698_0o8410.png[/img][/url][url=https://pixhost.to/show/132/200788699_9ogdf7.png][img=350x350]https://pixhost.to/show/132/200788699_9ogdf7.png[/img][/url]

_Originally posted by @ted423 in https://github.com/techmovie/easy-seed/issues/38#issuecomment-823164849_

**Comment by scatking** [comment]
这玩意虽然是个图片的url，但是响应的是个网页吧。 
实际上图片链接是：https://img53.pixhost.to/images/132/200788693_cz54s0.png
怪坑的

**Comment by techmovie** [comment]
> 这玩意虽然是个图片的url，但是响应的是个网页吧。
> 实际上图片链接是：https://img53.pixhost.to/images/132/200788693_cz54s0.png
> 怪坑的

对的 我是通过判断链接后缀来判断是不是真实图片地址 
需要把pixhost这种地址排除掉
