### ISSUE TITLE
[BUG] "invalid regexp group" Error

### ISSUE THREAD

**Issue by Purfview** [techmovie/easy-seed#55]
Script doesn't run on non-Chromium browsers (for example Waterfox Classic).

"invalid regexp group" Error on line 4831 (v1.2.4).
Looks like lookbehinds in RegExp is not supported everywhere.

JSfiddle will show problematic part: https://jsfiddle.net/5exh601L/  (you must run it on the browser where such RegExp is not supported, and press "Tidy" button)

**Comment by techmovie** [comment]
No consideration for support non-Chromium browsers for now.
By the way, you can create a new PR for support. LOL

**Comment by techmovie** [comment]
> Don't be lazy, it's just refactor of few characters on the one line. I don't even know why you need it, is it for Chinese titles? :)
Like `Gigolos.S06.720p.WEB-DL.DD+5.1.H.264-SLAG`,I would like to replace all dot to space，but I still want keep the dot which is in 5.1 or H.264.
non-Chromium browsers are like a black hole for me,you never know what problems it can cause.

> From what it does you would expect it to be called something like "easy-upload".
What you said makes sense,maybe I should change the name from next version.

**Comment by Purfview** [comment]
I didn't encountered any problems on non-Chromium browsers, imho Chrome should be banned too, everywhere... :trollface:

I guess I'll check that regex myself then.
If you rename it then use capitals "Easy-Upload", titles in English usually start with a capital letter.

**Comment by Purfview** [comment]
https://github.com/techmovie/easy-seed/pull/62
