### ISSUE TITLE
[BUG]Mt往外转的图片相关问题

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-seed#70]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：
* 浏览器版本：
* 所用用户脚本扩展名称：
* easy-seed版本：

**问题描述**
mt会有个图片缓存，使用转缩略图提示成功。然后转出还是带mt域名的

个人建议先预处理一下？
**复现步骤**

**问题截图**

**Comment by techmovie** [comment]
https://github.com/techmovie/easy-seed/commit/92e4078e1aaf51f80424b4cb29b5392f72a0af90
今天刚改过了
